### PR TITLE
Added button to download the Timetable and Subject Table

### PR DESCRIPTION
**Pull request by nattcodes**
Added options for the user to choose either to download both the timetable and subject table with PDF (using the jsPDF library) or JPEG(using the html2canvas library) #4 
screenshot-127 0 0 1_5500-2024 08 19-14_53_23

### CODE REVIEW

**Comment by Cyb3rGhoul** [comment]
@nattcodes Improve the Styling as it looks congested. The functionality works absolutely fine.

**Comment by Cyb3rGhoul** [comment]
Akso add the issue code in your PR as it will be easy for me to close the issue also.

**Comment by nattcodes** [comment]
> @nattcodes Improve the Styling as it looks congested. The functionality works absolutely fine.

Thank you, fixed it by increasing its margin 
screenshot-127 0 0 1_5500-2024 08 19-20_20_13

**Comment by nattcodes** [comment]
> @nattcodes Improve the Styling as it looks congested. The functionality works absolutely fine.



> Akso add the issue code in your PR as it will be easy for me to close the issue also.

okay, #4

**Pull request merged**
